src/main/resources/add-ons-to-index.json
Also this will test that CI runs on the PR
=> Add HFE module to the list

src/main/ui/app/route/Show.jsx, src/main/ui/app/sass/addonindex.scss
Just changed the size and added a little margin as well as removed some unwanted padding
=> Minor changes to font-awesome icons

src/main/resources/add-ons-to-index.json
Ref app section of addons will now show ref app 2.6 modules
=> Ref app modules updated to latest version 2.6

src/main/resources/add-ons-to-index.json
This PR basically fixes some minor index issues
=> Fixed some minor index issues

src/main/ui/app/component/ListOfLists.jsx, src/main/ui/app/route/About.jsx
The issue can be found here https://issues.openmrs.org/browse/AO-1
=> AO-1 : Adding an "About page" for Add-Ons

src/main/java/org/openmrs/addonindex/domain/AddOnInfoAndVersions.java, src/main/java/org/openmrs/addonindex/domain/AddOnToIndex.java, src/main/java/org/openmrs/addonindex/rest/AddOnController.java, src/main/java/org/openmrs/addonindex/scheduled/FetchDetailsToIndex.java, src/main/java/org/openmrs/addonindex/service/ElasticSearchIndex.java, src/main/java/org/openmrs/addonindex/service/Index.java, src/main/resources/add-ons-to-index.json, src/main/resources/elasticsearch/addOnInfoAndVersions-mappings.json, src/main/ui/package-lock.json, src/test/java/org/openmrs/addonindex/rest/AddOnControllerIT.java, src/test/java/org/openmrs/addonindex/scheduled/FetchDetailsToIndexTest.java, src/test/java/org/openmrs/addonindex/service/ElasticSearchIndexManualTest.java
List of changes:
1) Migrated all modules to use Bintray
2) Added two new fields called modulePackage and moduleId
3) Added new rest end points for accessing the modules using the above fields
4) Added tests for the same
=> AO 6 - Add additional rest end points

src/main/java/org/openmrs/addonindex/domain/AddOnInfoAndVersions.java, src/main/java/org/openmrs/addonindex/domain/artifactory/ArtifactoryFolderInfo.java, src/main/java/org/openmrs/addonindex/domain/artifactory/VersionList.java, src/main/java/org/openmrs/addonindex/rest/AddOnController.java, src/main/java/org/openmrs/addonindex/rest/artifactory/CoreVersionsController.java, src/main/java/org/openmrs/addonindex/scheduled/FetchCoreVersionsList.java, src/main/ui/app/component/SelectUserVersions.jsx, src/main/ui/app/route/App.jsx, src/main/ui/app/route/Show.jsx, src/main/ui/index.ejs, src/main/ui/package-lock.json, src/main/ui/package.json, src/test/java/org/openmrs/addonindex/domain/AddOnInfoAndVersionsTest.java, src/test/java/org/openmrs/addonindex/rest/CoreVersionsControllerIT.java, src/test/java/org/openmrs/addonindex/scheduled/FetchCoreVersionsListIT.java, src/test/resources/core-versions.json
This is the final additions to the Rest API for AO 4
=> AO 4 Fetch OpenMRS Core versions Rest API (Part 2) + UI

src/main/resources/add-ons-to-index.json
#Summary:
- Adds CohortBuilder to add-on index
=> Add Cohort Builder to addon index

src/main/resources/add-ons-to-index.json
Update the release of System Administration OWA.
Please find the related information [here](https://bintray.com/suthagar23/owa/openmrs-owa-sysadmin)  to merge this changes
=> Add System Administration OWA to AddOn Index

src/main/resources/add-ons-to-index.json
Issue: https://issues.openmrs.org/browse/GCI-179
=> [GCI-179] Add few tags to existing addons

src/main/resources/add-ons-to-index.json
https://issues.openmrs.org/browse/GCI-179
=> [GCI-179] Add relevant tags to OpenMRS AddOns modules

src/main/resources/add-ons-to-index.json
https://issues.openmrs.org/browse/GCI-179
I added tags for add-ons with no tags previously and added another tag to other add-ons.
=> [GCI-179]: Add relevant tags to OpenMRS Add-ons modules

src/main/resources/add-ons-to-index.json
=> Add Obsadmin to addon index

src/main/resources/add-ons-to-index.json
https://issues.openmrs.org/browse/GCI-258
I added corresponding icons to existing addons. All Refapp modules except Legacy UI and OWA module should have an icon now.
=> [GCI-258]: Add relevant icons to OpenMRS AddOns modules

src/main/resources/add-ons-to-index.json
This commit is to make AddOns index the OpenMRS Sync 2.0 module
=> Add OpenMRS Sync 2.0 to indexing

src/main/resources/add-ons-to-index.json
**SUMMARY**
Add Order Entry UI OWA to addon index list
Check [here](https://talk.openmrs.org/t/order-entry-ui-sprint-6-announcement/18351) for more information about the Order Entry UI OWA
=> OEUI: Add Order Entry UI OWA to addon index list

src/main/ui/package-lock.json, src/main/ui/package.json
Fix for security vulnerabilities and added a new dependency called babel-preset-stage-2
=> Fix for security vulnerabilities and added a new dependency called babel-preset-stage-2

src/main/resources/add-ons-to-index.json
request to add facelist module to the addon index
=> Request for the facelist module to be indexed by OpenMRS Addons

src/main/ui/index.ejs, src/main/ui/package-lock.json, src/main/ui/package.json
Made modifications to use react-select v1.x
=>  Made modifications to use react-select v1.x

src/main/resources/add-ons-to-index.json
I have just added some more information for the existing modules which are managed by myself.
=> Added more info to the developer and the LBAC, SysAdmin modules

src/main/resources/add-ons-to-index.json
Renamed VisitDocumentsUI module to Attachments Module
=> Renamed VisitDocumentsUI module to Attachments Module

src/main/resources/add-ons-to-index.json
Added Documentation And/Or Source Code Links for the following Addons for ticket AO-18:
1. Reference Application
2. Concept Management Apps
3. mdrtbpatientchartwidgets
4. metadata mapping module
5. neal reporting
6. remoteformentry
7. dhis2-reporting-module
8. ncd 1
9. Patient narratives
AO-18 Ticket Available  [here](https://issues.openmrs.org/browse/AO-18)
(the number above, next to the 'Commits' tab is 1).
No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`
existing code that was well tested you do not have to add tests)
No? -> write tests …
=> AO-18: Finished Source Code and Documentation Links

src/main/resources/add-ons-to-index.json, src/main/ui/package-lock.json
Issue: https://issues.openmrs.org/projects/AO/issues/AO-20
Made using the commits made by @anuar2k during GCI(updated a few module versions to match that released with 2.9). Thanks @anuar2k !
=> AO 20 Create list of Ref App 2.9 modules for AddOns

README.md
=> Minor formatting proposal on line 80

src/main/resources/add-ons-to-index.json
https://issues.openmrs.org/browse/AO-26
cc @dkayiwa
=> AO-26A:Create A List of RefApp 2.11 modules only for openmrs AddonIndex

src/main/resources/add-ons-to-index.json
Reverts openmrs/openmrs-contrib-addonindex#87
=> Revert "AO-26A:Create A List of RefApp 2.11 modules only for openmrs AddonIndex"

src/main/resources/add-ons-to-index.json
https://issues.openmrs.org/browse/AO-26
cc @dkayiwa 
So this ticket complises of only modules for refApp 2.11 only
=> AO-26B:Create A List of RefApp 2.11 modules only for openmrs AddonIndex

src/main/resources/add-ons-to-index.json
Ticket Id
[https://issues.openmrs.org/browse/AO-28](https://issues.openmrs.org/browse/AO-28)
=> Bindu | AO-28 | Add entires for Bed Management and Operation Theater modules for RefApp 2.11
